### ISSUE TITLE
Haven't heard from you for a long time :D

### ISSUE THREAD

**Issue by deanboole** [deanboole/abs#100]
Hi @goldie-lin 

How's it going? :smile:

**Comment by goldie-lin** [comment]
Hi @deanboole,
Sorry, 回覆晚了，前兩天搬家沒能馬上回覆。
我的翻譯部份，…這半年多因為一些私人因素變比較忙，
所以很不好意思，可能還會停滯一陣子，想休息一下，整理房間。

我前陣子又換工作，接著房東不續租、所以忙著找房子、看房子、搬家、… Orz

**Comment by goldie-lin** [comment]
噢，對了，PR# 破百了XD。

**Comment by deanboole** [comment]
Hi @goldie-lin 

辛苦你了，好好休息，讓身體心理都回血。
翻譯不急，充分休息好了再回來弄就好。

:smile:

**Comment by goldie-lin** [comment]
@deanboole:
Thanks. :+1:
