### ISSUE TITLE
確認一下

### ISSUE THREAD

**Issue by deanboole** [deanboole/abs#68]
Hi @goldie-lin 

ch4-1.md 我初稿翻完了，要繼續往下走
但我發現 KANBANG.md 上面「正在翻譯章節」上，您的部分是寫 ch4-2 .. ch5
這意思是從 ch4-2 到 ch5 中間 (還有 ch4-3 ch4-4) 以及 ch5 整個章節，您都要翻譯嗎？
還是只有 ch4-2 跟 ch5 整章節這兩部分呢？

如果只有這兩部分的話，我可以從 ch4-3 ch4-4 繼續翻喔 :+1:

**Comment by goldie-lin** [comment]
Hi @deanboole:
我本意是前者， 
(ch4-2, ch4-3, ch4-4, ch5, ch5-1, ch5-2)
目前我已翻完 ch4-2 跟 ch4-3 (已 merged)，
正在翻 ch4-4 中…。
不然就先留 ch4.x 系列讓我翻，OK嗎？
然後你要先從 ch5 接上或從 ch6 開始翻都可以。

BR,
Goldie.

**Comment by deanboole** [comment]
Hi @goldie-lin 

我就從 ch6 開始翻，ch5還是保留給你 :-)

**Comment by goldie-lin** [comment]
Ok. Got it! 謝啦 :D
