### ISSUE TITLE
Invitation as project collaborator

### ISSUE THREAD

**Issue by deanboole** [deanboole/abs#69]
Hi @goldie-lin 

想邀請您來 abs project 跟 Linux-tips project 當 collaborator。
我已經把您加入了 XD （希望您不會因為我這擅自的舉動感到不悅)

**Comment by goldie-lin** [comment]
Hi @deanboole:
我樂意幫忙！
完全不會不悅XD
謝啦 :-)

**Comment by deanboole** [comment]
Hi @goldie-lin 

好極了～ Good to have you la :-D
